[2025-01-13T16:23:17.734+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T16:23:17.746+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:22:00+00:00 [queued]>
[2025-01-13T16:23:17.753+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:22:00+00:00 [queued]>
[2025-01-13T16:23:17.756+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-13T16:23:17.769+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): append_to_database> on 2025-01-13 16:22:00+00:00
[2025-01-13T16:23:17.775+0000] {standard_task_runner.py:72} INFO - Started process 2980 to run task
[2025-01-13T16:23:17.778+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'stock_information', 'append_to_database', 'scheduled__2025-01-13T16:22:00+00:00', '--job-id', '431', '--raw', '--subdir', 'DAGS_FOLDER/vnstock_stream.py', '--cfg-path', '/tmp/tmpjx43lnnd']
[2025-01-13T16:23:17.781+0000] {standard_task_runner.py:105} INFO - Job 431: Subtask append_to_database
[2025-01-13T16:23:17.822+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:22:00+00:00 [running]> on host 453ac4defedc
[2025-01-13T16:23:17.902+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TuanDz' AIRFLOW_CTX_DAG_ID='stock_information' AIRFLOW_CTX_TASK_ID='append_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T16:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-13T16:22:00+00:00'
[2025-01-13T16:23:17.904+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T16:23:17.939+0000] {logging_mixin.py:190} INFO - Kết nối thành công!
[2025-01-13T16:23:17.940+0000] {logging_mixin.py:190} INFO - <class 'str'>
[2025-01-13T16:23:17.940+0000] {logging_mixin.py:190} INFO - None
[2025-01-13T16:23:17.941+0000] {logging_mixin.py:190} INFO - Có lỗi khi thực hiện append_database: The second parameter to executemany must be a sequence, iterator, or generator.
[2025-01-13T16:23:17.944+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-13T16:23:17.952+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T16:23:17.953+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_information, task_id=append_to_database, run_id=scheduled__2025-01-13T16:22:00+00:00, execution_date=20250113T162200, start_date=20250113T162317, end_date=20250113T162317
[2025-01-13T16:23:17.995+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T16:23:18.009+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-13T16:23:18.014+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
