[2025-01-10T17:35:04.069+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-10T17:35:04.081+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-10T17:34:00+00:00 [queued]>
[2025-01-10T17:35:04.089+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-10T17:34:00+00:00 [queued]>
[2025-01-10T17:35:04.091+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-10T17:35:04.104+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): append_to_database> on 2025-01-10 17:34:00+00:00
[2025-01-10T17:35:04.109+0000] {standard_task_runner.py:72} INFO - Started process 1841 to run task
[2025-01-10T17:35:04.112+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'stock_information', 'append_to_database', 'scheduled__2025-01-10T17:34:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/vnstock_stream.py', '--cfg-path', '/tmp/tmpkg9tzw6w']
[2025-01-10T17:35:04.114+0000] {standard_task_runner.py:105} INFO - Job 183: Subtask append_to_database
[2025-01-10T17:35:04.151+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_information.append_to_database scheduled__2025-01-10T17:34:00+00:00 [running]> on host 453ac4defedc
[2025-01-10T17:35:04.227+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TuanDz' AIRFLOW_CTX_DAG_ID='stock_information' AIRFLOW_CTX_TASK_ID='append_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T17:34:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-10T17:34:00+00:00'
[2025-01-10T17:35:04.228+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-10T17:35:04.281+0000] {logging_mixin.py:190} INFO - Lỗi kết nối db: ('08001', '[08001] [Microsoft][ODBC Driver 18 for SQL Server]SSL Provider: [error:0A000086:SSL routines::certificate verify failed:self-signed certificate] (-1) (SQLDriverConnect)')
[2025-01-10T17:35:04.282+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-10T17:35:04.290+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-10T17:35:04.292+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_information, task_id=append_to_database, run_id=scheduled__2025-01-10T17:34:00+00:00, execution_date=20250110T173400, start_date=20250110T173504, end_date=20250110T173504
[2025-01-10T17:35:04.326+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-10T17:35:04.346+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-10T17:35:04.352+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
