[2025-01-13T16:21:05.580+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T16:21:05.592+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:20:00+00:00 [queued]>
[2025-01-13T16:21:05.600+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:20:00+00:00 [queued]>
[2025-01-13T16:21:05.601+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-13T16:21:05.614+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): append_to_database> on 2025-01-13 16:20:00+00:00
[2025-01-13T16:21:05.622+0000] {standard_task_runner.py:72} INFO - Started process 2911 to run task
[2025-01-13T16:21:05.625+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'stock_information', 'append_to_database', 'scheduled__2025-01-13T16:20:00+00:00', '--job-id', '429', '--raw', '--subdir', 'DAGS_FOLDER/vnstock_stream.py', '--cfg-path', '/tmp/tmp404s59_p']
[2025-01-13T16:21:05.628+0000] {standard_task_runner.py:105} INFO - Job 429: Subtask append_to_database
[2025-01-13T16:21:05.668+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:20:00+00:00 [running]> on host 453ac4defedc
[2025-01-13T16:21:05.770+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TuanDz' AIRFLOW_CTX_DAG_ID='stock_information' AIRFLOW_CTX_TASK_ID='append_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T16:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-13T16:20:00+00:00'
[2025-01-13T16:21:05.773+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T16:21:05.819+0000] {logging_mixin.py:190} INFO - Kết nối thành công!
[2025-01-13T16:21:05.822+0000] {logging_mixin.py:190} INFO - <class 'str'>
[2025-01-13T16:21:05.824+0000] {logging_mixin.py:190} INFO - None
[2025-01-13T16:21:05.826+0000] {logging_mixin.py:190} INFO - Có lỗi khi thực hiện append_database: The second parameter to executemany must be a sequence, iterator, or generator.
[2025-01-13T16:21:05.837+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-13T16:21:05.846+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T16:21:05.849+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_information, task_id=append_to_database, run_id=scheduled__2025-01-13T16:20:00+00:00, execution_date=20250113T162000, start_date=20250113T162105, end_date=20250113T162105
[2025-01-13T16:21:05.880+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T16:21:05.894+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-13T16:21:05.898+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
